# -*- coding: utf-8 -*-
"""modelling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C05nJVoDM_1ceguxlGeN5MTT5qxKLr5b

# **IMPORT LIBRARY**
"""

!pip install mlflow

import pandas as pd
import mlflow
import mlflow.sklearn

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

"""# **DATASET LOADING**"""

df = pd.read_csv("train_preprocessing.csv")

X = df.drop("Class", axis=1)
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""# **MLFLOW**"""

mlflow.set_experiment(
    "Credit Card Fraud Detection"
)

mlflow.sklearn.autolog()



# Training Model
with mlflow.start_run():

    model = RandomForestClassifier(
        random_state=42
    )

    model.fit(
        X_train,
        y_train
    )

    y_pred = model.predict(
        X_test
    )

    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    print(
        "Accuracy :",
        accuracy
    )
